#!/bin/bash
set -e

# ============================================================
# TorrenClou All-in-One Entrypoint
#
# Generates its own secrets, initializes PostgreSQL, exports the runtime
# configuration and starts supervisord.
#
# Nothing here is required from the environment. Every variable below is an
# optional override: if you set one, it wins; if you do not, a sensible value is
# derived or generated. That is what makes `docker run` with no --env-file work.
# ============================================================

PGDATA="/data/postgres"

# The secrets file lives INSIDE the PostgreSQL volume, not at /data.
# /data itself is the container's writable layer — only the subdirectories are
# mounted — so a file there is destroyed by `docker rm`, which every upgrade
# does. That silently rotated the signing keys and logged everyone out.
SECRETS_FILE="$PGDATA/secrets.env"

# -----------------------------------------------------------
# 0. Secrets
#
# Generated once and kept on the data volume, so they survive `docker rm` and
# image upgrades. Losing that volume invalidates every session and login token.
# Anything already set in the environment is left alone.
#
# The values are decided here but the file is only written after PostgreSQL has
# been initialized: initdb refuses a non-empty data directory, so writing it
# first would break the very first boot.
# -----------------------------------------------------------
generate_secret() {
    openssl rand -base64 "$1" | tr -dc "A-Za-z0-9" | cut -c1-"$2"
}

if [ -f "$SECRETS_FILE" ]; then
    # shellcheck disable=SC1090
    . "$SECRETS_FILE"
    WRITE_SECRETS=0
else
    echo "[entrypoint] First run — generating secrets"
    GENERATED_POSTGRES_PASSWORD=$(generate_secret 24 24)
    GENERATED_JWT_SECRET=$(generate_secret 48 48)
    GENERATED_NEXTAUTH_SECRET=$(generate_secret 48 48)
    GENERATED_GRAFANA_PASSWORD=$(generate_secret 16 16)
    WRITE_SECRETS=1
fi

# Explicit values win over the generated ones in every case.
POSTGRES_DB="${POSTGRES_DB:-torrenclo}"
POSTGRES_USER="${POSTGRES_USER:-torrenclo_user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$GENERATED_POSTGRES_PASSWORD}"
JWT_SECRET="${JWT_SECRET:-$GENERATED_JWT_SECRET}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-$GENERATED_NEXTAUTH_SECRET}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-$GENERATED_GRAFANA_PASSWORD}"

PGBIN="/usr/lib/postgresql/15/bin"

# -----------------------------------------------------------
# 1. Initialize PostgreSQL if data directory is empty
# -----------------------------------------------------------
if [ ! -f "$PGDATA/PG_VERSION" ]; then
    echo "[entrypoint] Initializing PostgreSQL data directory..."
    chown -R postgres:postgres "$PGDATA"
    su - postgres -c "$PGBIN/initdb -D $PGDATA --encoding=UTF8 --locale=C"

    cat >> "$PGDATA/postgresql.conf" <<EOF
listen_addresses = '127.0.0.1'
port = 5432
max_connections = 200
shared_buffers = 128MB
EOF

    cat > "$PGDATA/pg_hba.conf" <<EOF
local   all   all                 trust
host    all   all   127.0.0.1/32  md5
host    all   all   ::1/128       md5
EOF

    su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -w start"
    su - postgres -c "psql -p 5432 -c \"CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';\""
    su - postgres -c "psql -p 5432 -c \"CREATE DATABASE $POSTGRES_DB OWNER $POSTGRES_USER;\""
    su - postgres -c "psql -p 5432 -c \"GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;\""
    su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -w stop"

    echo "[entrypoint] PostgreSQL initialized successfully."
else
    echo "[entrypoint] PostgreSQL data directory exists, skipping init."
    chown -R postgres:postgres "$PGDATA"
fi

# The data directory exists now, so the secrets file can safely live in it.
if [ "$WRITE_SECRETS" = "1" ]; then
    umask 077
    cat > "$SECRETS_FILE" <<EOF
# Generated by TorrenClou on first run. Keep this file.
# Deleting it logs everyone out and orphans the PostgreSQL password.
GENERATED_POSTGRES_PASSWORD=$GENERATED_POSTGRES_PASSWORD
GENERATED_JWT_SECRET=$GENERATED_JWT_SECRET
GENERATED_NEXTAUTH_SECRET=$GENERATED_NEXTAUTH_SECRET
GENERATED_GRAFANA_PASSWORD=$GENERATED_GRAFANA_PASSWORD
EOF
    chmod 600 "$SECRETS_FILE"
    chown postgres:postgres "$SECRETS_FILE"
    echo "[entrypoint] Secrets written to $SECRETS_FILE"
fi

# Always enforce correct PostgreSQL port (data volume may have stale config)
sed -i 's/^port = .*/port = 5432/' "$PGDATA/postgresql.conf"

# -----------------------------------------------------------
# 2. Sync credentials and read the settings the app owns
#
# Worker count and the observability toggles are edited in the Settings tab but
# only read at process start, so this is where a change made in the UI takes
# effect. On a first boot the table does not exist yet and the defaults apply.
# -----------------------------------------------------------
echo "[entrypoint] Syncing PostgreSQL credentials..."
su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -w start"
su - postgres -c "psql -p 5432 -c \"ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';\""

read_setting() {
    su - postgres -c "psql -p 5432 -d $POSTGRES_DB -tAc \
        'SELECT \"$1\" FROM dev.\"SystemSettings\" ORDER BY \"Id\" LIMIT 1'" 2>/dev/null | tr -d '[:space:]'
}

DB_WORKER_COUNT=$(read_setting "HangfireWorkerCount" || true)
DB_ENABLE_PROMETHEUS=$(read_setting "EnablePrometheus" || true)
DB_ENABLE_TRACING=$(read_setting "EnableTracing" || true)

su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -w stop"

# PostgreSQL prints booleans as t/f; the .NET configuration binder wants true/false.
pg_bool() {
    case "$1" in
        t) echo "true" ;;
        f) echo "false" ;;
        *) echo "$2" ;;
    esac
}

if [ -n "$DB_WORKER_COUNT" ]; then
    echo "[entrypoint] Using worker count from Settings: $DB_WORKER_COUNT"
fi

# -----------------------------------------------------------
# 3. Ensure directory permissions
# -----------------------------------------------------------
chown -R redis:redis /data/redis
mkdir -p /data/downloads /data/prometheus /data/grafana
chmod 777 /data/downloads
chown -R grafana:grafana /data/grafana

# -----------------------------------------------------------
# 4. Export environment variables for .NET services
# -----------------------------------------------------------
export ConnectionStrings__DefaultConnection="Host=127.0.0.1;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
export Redis__ConnectionString="127.0.0.1:6379"
export APPLY_MIGRATIONS="${APPLY_MIGRATIONS:-true}"
export ASPNETCORE_ENVIRONMENT="${ASPNETCORE_ENVIRONMENT:-Production}"
export TORRENT_DOWNLOAD_PATH="/data/downloads"

# Settings tab first, then the environment override, then the default.
export Hangfire__WorkerCount="${DB_WORKER_COUNT:-${HANGFIRE_WORKER_COUNT:-10}}"

# JWT
export Jwt__Key="${JWT_SECRET}"
export Jwt__Issuer="${JWT_ISSUER:-TorrenClou_API}"
export Jwt__Audience="${JWT_AUDIENCE:-TorrenClou_Client}"

# Admin credentials
#
# Not set by default. The first-run wizard creates the account and stores the
# password hashed. These are honoured only as a bootstrap for installs that
# predate the wizard, and setting them disables the wizard entirely.
# Exported only when actually set. A bare `[ -n "$X" ] && export X` would return
# non-zero on an unset variable and, under `set -e`, kill the container at boot.
if [ -n "${ADMIN_EMAIL:-}" ]; then export ADMIN_EMAIL; fi
if [ -n "${ADMIN_PASSWORD:-}" ]; then export ADMIN_PASSWORD; fi
if [ -n "${ADMIN_NAME:-}" ]; then export ADMIN_NAME; fi

# Public URL
#
# Left unset on purpose. The API derives it from the host the request arrived on
# and next-auth does the same via AUTH_TRUST_HOST, so the container does not need
# to be told its own address. Set these only behind a proxy that rewrites the host.
if [ -z "${FRONTEND_URL:-}" ] && [ -n "${PUBLIC_FRONTEND_URL:-}" ]; then
    FRONTEND_URL="$PUBLIC_FRONTEND_URL"
fi
if [ -n "${FRONTEND_URL:-}" ]; then export FRONTEND_URL; fi
if [ -n "${NEXTAUTH_URL:-}" ]; then export NEXTAUTH_URL; fi

# Next.js server-side runtime vars
export BACKEND_URL="${BACKEND_URL:-http://127.0.0.1:47200}"
export NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
export AUTH_TRUST_HOST=true

# Observability (optional)
export Observability__LokiUrl="${OBSERVABILITY_LOKI_URL:-}"
export Observability__LokiUsername="${OBSERVABILITY_LOKI_USERNAME:-}"
export Observability__LokiApiKey="${OBSERVABILITY_LOKI_API_KEY:-}"
export Observability__OtlpEndpoint="${OBSERVABILITY_OTLP_ENDPOINT:-}"
export Observability__OtlpHeaders="${OBSERVABILITY_OTLP_HEADERS:-}"
export Observability__EnablePrometheus="$(pg_bool "$DB_ENABLE_PROMETHEUS" "${OBSERVABILITY_ENABLE_PROMETHEUS:-true}")"
export Observability__EnableTracing="$(pg_bool "$DB_ENABLE_TRACING" "${OBSERVABILITY_ENABLE_TRACING:-true}")"

# Grafana
export GF_SECURITY_ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
export GF_SECURITY_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}"
export GF_SERVER_HTTP_PORT=47500
_GRAFANA_BASE=$(echo "${PUBLIC_FRONTEND_URL:-http://localhost}" | sed 's|:[0-9]*$||')
export GF_SERVER_ROOT_URL="${_GRAFANA_BASE}:47500"

# .NET Runtime settings
export DOTNET_gcServer=1
export DOTNET_EnableDiagnostics=0
export TMPDIR=/app/tmp
export TEMP=/app/tmp
export TMP=/app/tmp
export DOTNET_BUNDLE_EXTRACT_BASE_DIR=/app/tmp/bundle

# -----------------------------------------------------------
# 5. Start all services via supervisord
# -----------------------------------------------------------
echo "[entrypoint] Starting all services..."
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/torrencloud.conf
